project_name: myproject
release:
  github:
    owner: sundowndev
    name: goreleaser-template
  draft: true
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "myproject-build"
    binary: myproject
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
