project_name: myproject
release:
  github:
    owner: sundowndev
    name: goreleaser-template
  draft: true
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "myproject-build"
    binary: myproject
    dir: .
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags: -s -w -X github.com/cloudskiff/driftctl/build.env=release -X github.com/sundowndev/goreleaser-template.version={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
